apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/AxlRoe/app-test #configure: change if you want to build something else, perhaps from your own local git repository.
