apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-pr-pipeline
spec:
  resources:
    - name: skaffold-git
      type: git
    - name: pippo-image
      type: image
  tasks:
    - name: build-docker-image-from-git-source
      taskRef:
        name: build-docker-image-from-git-source
      resources:
        inputs:
          - name: skaffold-git
            resource: skaffold-git
        outputs:
          - name: pippo-image
            resource: pippo-image
