apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: skaffold-image-leeroy-web
spec:
  type: image
  params:
    - name: url
      value: europe-west2-docker.pkg.dev/tekton-test-321920/tekton-test-repo/app-test #configure: replace with where the image should go: perhaps your local registry or Dockerhub with a secret and configured service account

