apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-pr-pipeline-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-pr-pipeline-run-
      spec:
        serviceAccountName: tekton-triggers-example-sa
        pipelineRef:
          name: github-pr-pipeline
        resources:
          - name: git-source
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: main
                - name: url
                  value: https://github.com/AxlRoe/app-test
          - name: docker-image
            resourceSpec:
              type: image
              params:
                - name: dockerimageurl
                  value: europe-west2-docker.pkg.dev/tekton-test-321920/tekton-test-repo/app-test
