apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: gitrepositoryurl
      value: https://github.com/AxlRoe/app-test
    - name: gitrevision
      value: main
    - name: dockerimageurl
      value: europe-west2-docker.pkg.dev/tekton-test-321920/tekton-test-repo/app-test
