apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-pr-pipeline-template
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
    - name: dockerimageurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: git-source
        namespace: tekton-argocd-example
      spec:
        type: git
        params:
          - name: revision
            value: $(tt.params.gitrevision)
          - name: url
            value: $(tt.params.gitrepositoryurl) #configure: change if you want to build something else, perhaps from your own local git repository.
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: docker-image
        namespace: tekton-argocd-example
      spec:
        type: image
        params:
          - name: url
            value: $(tt.params.dockerimageurl) #configure: replace with where the image should go: perhaps your local registry or Dockerhub with a secret and configured service account
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: github-pr-pipeline-run-
        namespace: tekton-argocd-example
      spec:
        serviceAccountName: pipeline-sa
        pipelineRef:
          name: github-pr-pipeline
        resources:
        - name: git-source
          resourceRef: git-source
        - name: docker-image
          resourceRef: docker-image
