apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-pr-binding
spec:
  params:
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: gitrevision
      value: $(body.pull_request.head.sha)
    - name: dockerimageurl
      value: europe-west2-docker.pkg.dev/tekton-test-321920/tekton-test-repo/app-test