apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-pr-pipeline-template
spec:
  params:
   - name: gitrevision
   - name: gitrepositoryurl
   - name: dockerimageurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: github-pr-pipeline-run-
      spec:
        serviceAccountName: tekton-triggers-example-sa
        pipelineRef:
          name: github-pr-pipeline
        resources:
          - name: git-source
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(tt.params.gitrevision)
                - name: url
                  value: $(tt.params.gitrepositoryurl)
          - name: docker-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.dockerimageurl)
